// RPC Constants for VOIDLINE PVP Zone System

enum VoidlineERPCs
{
    VOIDLINE_RPC_ZONE_DATA = 95001,
    VOIDLINE_RPC_ZONE_ENTRY = 95002,
    VOIDLINE_RPC_ZONE_EXIT = 95003,
    VOIDLINE_RPC_ZONE_VISIBILITY = 95004,
    VOIDLINE_RPC_REQUEST_DATA = 95005
}
